name: publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Setup node
        uses: actions/setup-node@v2.0.0
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org
      - run: |
          npm ci
          npm run prerelease
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
